test custom action

diff --git a/.github/workflows/publish-mavencentral.yaml b/.github/workflows/publish-mavencentral.yaml
--- a/.github/workflows/publish-mavencentral.yaml
+++ b/.github/workflows/publish-mavencentral.yaml
@@ -1,8 +1,10 @@
 name: Build and push to MavenCentral
 on:
   push:
-    tags:
-      - 0.*
+    branches:
+      - publish_play
+#    tags:
+#      - 0.*
 
 jobs:
   publish:
@@ -23,7 +25,7 @@ jobs:
         uses: actions/setup-java@v4
         with:
           java-version: '17'
-          distribution: 'adopt'
+          distribution: 'temurin'
       - name: Validate Gradle wrapper
         uses: gradle/wrapper-validation-action@699bb18358f12c5b78b37bb0111d3a0e2276e0e2
         # 2.1.1
@@ -76,31 +78,36 @@ jobs:
       # Crude upload inspired by https://mccue.dev/pages/6-1-22-upload-to-maven-central
       # Avoids sharing credentials with all Gradle plugins/potential annotation processors
       - name: Upload and Release Bundle
-        env:
-          USERNAME: ${{ secrets.OSSRH_USERNAME }}
-          PASSWORD: ${{ secrets.OSSRH_TOKEN }}
-        run: |
-          curl --request GET --url https://s01.oss.sonatype.org/service/local/authentication/login \
-               --cookie-jar cookies.txt --user "${USERNAME}:${PASSWORD}"
-          repoMetadataId=$(curl --request POST --url https://s01.oss.sonatype.org/service/local/staging/bundle_upload \
-               --cookie cookies.txt --header 'Content-Type: multipart/form-data' \
-               --form file=@/tmp/bundle-metadata.jar | jq -r ".repositoryUris[0]" | sed 's/.*\///')
-          repoPluginId=$(curl --request POST --url https://s01.oss.sonatype.org/service/local/staging/bundle_upload \
-               --cookie cookies.txt --header 'Content-Type: multipart/form-data' \
-               --form file=@/tmp/bundle-plugin.jar | jq -r ".repositoryUris[0]" | sed 's/.*\///')
-          echo "Wait for repos '$repoMetadataId', and '$repoPluginId' to settle.."
-          # should probe for state change:
-          #  curl -v -H 'Accept: application/json' /tmp/cookies.txt https://s01.oss.sonatype.org/service/local/staging/repository/dkmada-1104
-          #  Look for type:closed
-          sleep 150
-          echo "Publish NOT completed! Test repo!"
-          # release - unless tag starts with 0.0.
-          echo $BUILD_LABEL | grep -q -v -e "^0[.]0[.]" \
-            && curl --request POST \
-               --url https://s01.oss.sonatype.org/service/local/staging/bulk/promote \
-               --cookie cookies.txt \
-               --header 'Content-Type: application/json' \
-               --data "{ 'data': { 'autoDropAfterRelease': true, 'description': '', 'stagedRepositoryIds': ['$repoMetadataId', '$repoPluginId'] } }" \
-            && echo "Publish completed" \
-            || echo "Publish skipped / failed"
-          rm -f cookies.txt
+        uses: jskov/action-nexus-publish@test
+        with:
+          signing_key: 'some magic secret key'
+          signing_key_secret: 'and its secret'
+
+#        env:
+#          USERNAME: ${{ secrets.OSSRH_USERNAME }}
+#          PASSWORD: ${{ secrets.OSSRH_TOKEN }}
+#        run: |
+#          curl --request GET --url https://s01.oss.sonatype.org/service/local/authentication/login \
+#               --cookie-jar cookies.txt --user "${USERNAME}:${PASSWORD}"
+#          repoMetadataId=$(curl --request POST --url https://s01.oss.sonatype.org/service/local/staging/bundle_upload \
+#               --cookie cookies.txt --header 'Content-Type: multipart/form-data' \
+#               --form file=@/tmp/bundle-metadata.jar | jq -r ".repositoryUris[0]" | sed 's/.*\///')
+#          repoPluginId=$(curl --request POST --url https://s01.oss.sonatype.org/service/local/staging/bundle_upload \
+#               --cookie cookies.txt --header 'Content-Type: multipart/form-data' \
+#               --form file=@/tmp/bundle-plugin.jar | jq -r ".repositoryUris[0]" | sed 's/.*\///')
+#          echo "Wait for repos '$repoMetadataId', and '$repoPluginId' to settle.."
+#          # should probe for state change:
+#          #  curl -v -H 'Accept: application/json' /tmp/cookies.txt https://s01.oss.sonatype.org/service/local/staging/repository/dkmada-1104
+#          #  Look for type:closed
+#          sleep 150
+#          echo "Publish NOT completed! Test repo!"
+#          # release - unless tag starts with 0.0.
+#          echo $BUILD_LABEL | grep -q -v -e "^0[.]0[.]" \
+#            && curl --request POST \
+#               --url https://s01.oss.sonatype.org/service/local/staging/bulk/promote \
+#               --cookie cookies.txt \
+#               --header 'Content-Type: application/json' \
+#               --data "{ 'data': { 'autoDropAfterRelease': true, 'description': '', 'stagedRepositoryIds': ['$repoMetadataId', '$repoPluginId'] } }" \
+#            && echo "Publish completed" \
+#            || echo "Publish skipped / failed"
+#          rm -f cookies.txt
